// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeasfunzngepwiulqgjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYXNmdW56bmdlcHdpdWxxZ2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjg5NTcsImV4cCI6MjA2NTgwNDk1N30.fsxRA4FlpebiNJ6WWRE-PkOcF1snEamnENIHzT-2_KA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);